- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: soumyadevops.space
    instances:
    - db
    - backend
    - frontend
  tasks: 
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-all #replace with your AWS values
      image_id: ami-09c813fb71547fc4f #replace with your AWS values
      tags:
        Name: "{{ item }}"
    loop:
    - "{{ instances }}"
    register: ec2_instances_info

  - name: print output
    ansible.builtin.debug:
      msg: "output: {{ ec2_instances_info }}"  
    
  - name: create r53 records
    amazon.aws.route53: 
      state: present
      zone: " {{ zone }}"
      record: " {{ item }}.{{ zone }}"
      type: A     
      value: "{{ item.private_ip_address }}"
      overwrite: true
      ttl: 1
    loop: "{{ results.instances }}"
